config/routes.rb
BlogMinitest::Application.routes.draw do
  resources :foos

  resources :thingies

  resources :articles

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/foo.rb
class Foo < ActiveRecord::Base
end

app/models/thingy.rb
class Thingy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/foos_controller.rb
class FoosController < ApplicationController
  # GET /foos
  # GET /foos.json
  def index
    @foos = Foo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foos }
    end
  end

  # GET /foos/1
  # GET /foos/1.json
  def show
    @foo = Foo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/new
  # GET /foos/new.json
  def new
    @foo = Foo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foo }
    end
  end

  # GET /foos/1/edit
  def edit
    @foo = Foo.find(params[:id])
  end

  # POST /foos
  # POST /foos.json
  def create
    @foo = Foo.new(params[:foo])

    respond_to do |format|
      if @foo.save
        format.html { redirect_to @foo, notice: 'Foo was successfully created.' }
        format.json { render json: @foo, status: :created, location: @foo }
      else
        format.html { render action: "new" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foos/1
  # PUT /foos/1.json
  def update
    @foo = Foo.find(params[:id])

    respond_to do |format|
      if @foo.update_attributes(params[:foo])
        format.html { redirect_to @foo, notice: 'Foo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @foo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foos/1
  # DELETE /foos/1.json
  def destroy
    @foo = Foo.find(params[:id])
    @foo.destroy

    respond_to do |format|
      format.html { redirect_to foos_url }
      format.json { head :ok }
    end
  end
end

app/controllers/thingies_controller.rb
class ThingiesController < ApplicationController
  # GET /thingies
  # GET /thingies.json
  def index
    @thingies = Thingy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @thingies }
    end
  end

  # GET /thingies/1
  # GET /thingies/1.json
  def show
    @thingy = Thingy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thingy }
    end
  end

  # GET /thingies/new
  # GET /thingies/new.json
  def new
    @thingy = Thingy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thingy }
    end
  end

  # GET /thingies/1/edit
  def edit
    @thingy = Thingy.find(params[:id])
  end

  # POST /thingies
  # POST /thingies.json
  def create
    @thingy = Thingy.new(params[:thingy])

    respond_to do |format|
      if @thingy.save
        format.html { redirect_to @thingy, notice: 'Thingy was successfully created.' }
        format.json { render json: @thingy, status: :created, location: @thingy }
      else
        format.html { render action: "new" }
        format.json { render json: @thingy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /thingies/1
  # PUT /thingies/1.json
  def update
    @thingy = Thingy.find(params[:id])

    respond_to do |format|
      if @thingy.update_attributes(params[:thingy])
        format.html { redirect_to @thingy, notice: 'Thingy was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @thingy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thingies/1
  # DELETE /thingies/1.json
  def destroy
    @thingy = Thingy.find(params[:id])
    @thingy.destroy

    respond_to do |format|
      format.html { redirect_to thingies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/foos_helper.rb
module FoosHelper
end

app/helpers/thingies_helper.rb
module ThingiesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.content %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/foos/_form.html.erb
<%= form_for(@foo) do |f| %>
  <% if @foo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foo.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% @foo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foos/edit.html.erb
<h1>Editing foo</h1>

<%= render 'form' %>

<%= link_to 'Show', @foo %> |
<%= link_to 'Back', foos_path %>

app/views/foos/index.html.erb
<h1>Listing foos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foos.each do |foo| %>
  <tr>
    <td><%= foo.title %></td>
    <td><%= foo.content %></td>
    <td><%= link_to 'Show', foo %></td>
    <td><%= link_to 'Edit', edit_foo_path(foo) %></td>
    <td><%= link_to 'Destroy', foo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foo', new_foo_path %>

app/views/foos/new.html.erb
<h1>New foo</h1>

<%= render 'form' %>

<%= link_to 'Back', foos_path %>

app/views/foos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @foo.title %>
</p>

<p>
  <b>Content:</b>
  <%= @foo.content %>
</p>


<%= link_to 'Edit', edit_foo_path(@foo) %> |
<%= link_to 'Back', foos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogMinitest</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thingies/_form.html.erb
<%= form_for(@thingy) do |f| %>
  <% if @thingy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thingy.errors.count, "error") %> prohibited this thingy from being saved:</h2>

      <ul>
      <% @thingy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thingies/edit.html.erb
<h1>Editing thingy</h1>

<%= render 'form' %>

<%= link_to 'Show', @thingy %> |
<%= link_to 'Back', thingies_path %>

app/views/thingies/index.html.erb
<h1>Listing thingies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @thingies.each do |thingy| %>
  <tr>
    <td><%= thingy.title %></td>
    <td><%= thingy.content %></td>
    <td><%= link_to 'Show', thingy %></td>
    <td><%= link_to 'Edit', edit_thingy_path(thingy) %></td>
    <td><%= link_to 'Destroy', thingy, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thingy', new_thingy_path %>

app/views/thingies/new.html.erb
<h1>New thingy</h1>

<%= render 'form' %>

<%= link_to 'Back', thingies_path %>

app/views/thingies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @thingy.title %>
</p>

<p>
  <b>Content:</b>
  <%= @thingy.content %>
</p>


<%= link_to 'Edit', edit_thingy_path(@thingy) %> |
<%= link_to 'Back', thingies_path %>